### ISSUE TITLE
td.Block.__rrshift__(lhs) v. td.Block.__rshift__(rhs)

### ISSUE THREAD

**Issue by ch3njust1n** [tensorflow/fold#35]
What's the difference between `td.Block.__rrshift__(lhs)` and `td.Block.__rshift__(rhs)`. According to the documentation, they're the same thing.
[Blocks API](https://github.com/tensorflow/fold/blob/master/tensorflow_fold/g3doc/py/td.md#tdblock__rrshift__lhs)

**Comment by moshelooks** [comment]
They are the same thing. In Python if you say 'a >> b' then you get
a.__rshift(b) if a has a right shift operator, or b.__rrshift(a) as a
fallback. We support the fallback so that e.g.

tensor >> foo

will do the right thing when 'tensor' is a tensor and foo is a block; this
is equivalent to

td.ConvertToTensor(tensor) >> foo

(see convert_to_block
<https://github.com/tensorflow/fold/blob/master/tensorflow_fold/g3doc/py/td.md#td.convert_to_block>
for details on the conversion). This is a reasonable conversion because >>
is one of the few operators that tf Tensor never overloads.

**Comment by ch3njust1n** [comment]
Ok thanks for the clarification
